//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CRUDEntityFrameworkCars
{
    using System;
    using System.Collections.Generic;
    
    public partial class Car
    {
        public int id { get; set; }
        public string brand { get; set; }
        public string model { get; set; }
        public Nullable<int> speed { get; set; }
        public Nullable<int> price { get; set; }
        public Nullable<int> year { get; set; }
        public string photo { get; set; }
    }
}
