//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planes
    {
        public int Id { get; set; }
        public string Model { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<int> Speed { get; set; }
        public Nullable<int> ManufacturerId { get; set; }
    }
}
